export const FETCH_COUNTRIES_NAME_SUCCESS: string =
  'FETCH_COUNTRIES_NAME_SUCCESS';
export const FETCH_COUNTRIES_NAME_REQUEST: string =
  'FETCH_COUNTRIES_NAME_REQUEST';
export const FETCH_COUNTRIES_NAME_ERROR: string = 'FETCH_COUNTRIES_NAME_ERROR';
