export const FETCH_COUNTRIES_NAME_SUCCESS = 'FETCH_COUNTRIES_NAME_SUCCESS'
export const FETCH_COUNTRIES_NAME_REQUEST = 'FETCH_COUNTRIES_NAME_REQUEST'
export const FETCH_COUNTRIES_NAME_ERROR = 'FETCH_COUNTRIES_NAME_ERROR'