export const FETCH_HISTORY_DATA_REQUEST: string = 'FETCH_HISTORY_DATA_REQUEST';
export const FETCH_HISTORY_DATA_SUCCESS: string = 'FETCH_HISTORY_DATA_SUCCESS';
export const FETCH_HISTORY_DATA_ERROR: string = 'FETCH_HISTORY_DATA_ERROR';
