export const FETCH_COUNTRY_DATA_SUCCESS: string = 'FETCH_COUNTRY_DATA_SUCCESS';
export const FETCH_GLOBAL_DATA_SUCCESS: string = 'FETCH_GLOBAL_DATA_SUCCESS';
export const FETCH_COVID_DATA_REQUEST: string = 'FETCH_COVID_DATA_REQUEST';
export const FETCH_COVID_DATA_ERROR: string = 'FETCH_COVID_DATA_ERROR';
export const SET_SELECTED_COUNTRY: string = 'SET_SELECTED_COUNTRY';
